### ISSUE TITLE
Phonegap Build

### ISSUE THREAD

**Issue by tmdevde** [Festify/cordova-spotify-oauth#19]
Hi, i'm working with phonegap build and i get following error while creating a build:

```
Error - Plugin error (you probably need to remove plugin files from your app): 
Fetching plugin "cordova-spotify-oauth" via npm Installing "cordova-spotify-oauth" at "0.1.11" for ios 
Fetching plugin "es6-promise-plugin" via npm Installing "es6-promise-plugin" at "4.2.2" for ios 
Fetching plugin "cordova-plugin-add-swift-support@1.6.1" via npm Installing "cordova-plugin-add-swift-support" at "1.6.1" for ios 

Error during processing of action! Attempting to revert... Failed to install 'cordova-spotify-oauth': 

CordovaError: Uh oh! Cannot find framework 
"/private/tmp/gimlet/3178773/project/cordova/plugins/cordova-spotify-oauth/src/ios/spotify-sdk/SpotifyAuthentication.framework" for plugin cordova-spotify-oauth
in iOS platform at install 
(/private/tmp/gimlet/3178773/project/cordova/lib/plugman/pluginHandlers.js:109:48)
at ActionStack.process (/private/tmp/gimlet/3178773/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25) at PluginManager.doOperation 
(/private/tmp/gimlet/3178773/project/cordova/node_modules/cordova-common/src/PluginManager.js:114:20) at PluginManager.addPlugin 
(/private/tmp/gimlet/3178773/project/cordova/node_modules/cordova-common/src/PluginManager.js:144:17) at Api.addPlugin 
(/private/tmp/gimlet/3178773/project/cordova/Api.js:234:10) at handleInstall 
(/usr/local/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:594:10) at /usr/local/lib/node_modules/pgb-plugman-151/node_modules/pgb-cordova-lib/src/plugman/install.js:357:28 at _fulfilled
(/usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:787:54) at
/usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:816:30 at
Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman-151/node_modules/q/q.js:749:13) 
Uh oh! Cannot find framework "/private/tmp/gimlet/3178773/project/cordova/plugins/cordova-spotify-oauth/src/ios/spotify-sdk/SpotifyAuthentication.framework" 
for plugin cordova-spotify-oauth in iOS platform
```

Anything i can do?
```
<gap:plugin name="cordova-spotify-oauth" source="npm" />
```

**Comment by tmdevde** [comment]
Still getting the same error.

**Comment by am5815** [comment]
Any update on this? I'm getting this error now
