### ISSUE TITLE
Failed to install since latest merge

### ISSUE THREAD

**Issue by duffdean** [Festify/cordova-spotify-oauth#33]
Hi i am hoping someone can help. First of all thanks for updating the plugin with the removal of the legacy Spotify SDK as this is the best plugin out there.

So it seems as though since the latest merge to resolve the legacy SDK issue i am no longer able to install the plugin. I have even tried on a brand new empty cordova project and i get the same error message.

I am currently running:
Cordova 8.1.2 (cordova-lib@8.1.1)
iOS 5.1.1

The issue i am receiving seems to reference install-ios.sh which i thought was removed? Here is the output of the terminal whenever i call 'cordova plugins add cordova-spotify-oauth'

> Dean-Air:cordovatestproject duffdean$ cordova plugins add cordova-spotify-oauth
Installing "cordova-spotify-oauth" for ios
Dependent plugin "es6-promise-plugin" already installed on ios.
Plugin dependency "cordova-plugin-add-swift-support@2.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-add-swift-support" already installed on ios.
Running command: /Users/duffdean/cordovatestproject/plugins/cordova-spotify-oauth/install-ios.sh /Users/duffdean/cordovatestproject
tar: Error opening archive: Unrecognized archive format
Failed to install 'cordova-spotify-oauth': Error: Hook failed with error code 1: /Users/duffdean/cordovatestproject/plugins/cordova-spotify-oauth/install-ios.sh
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:239:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Hook failed with error code 1: /Users/duffdean/cordovatestproject/plugins/cordova-spotify-oauth/install-ios.sh

Any help would be greatly appreciated!

Thanks

**Comment by manuelsc** [comment]
As far as I know they haven't published a new version with the fix yet, so you are still running on the old version. You can install the new version directly from source though:

`npm install github:Festify/cordova-spotify-oauth`

**Comment by duffdean** [comment]
> As far as I know they haven't published a new version with the fix yet, so you are still running on the old version. You can install the new version directly from source though:
> 
> `npm install github:Festify/cordova-spotify-oauth`

Could you point me in the right direction as to how i would install this using the above method? By performing `cordova plugins add cordova-spotify-oauth ` it always uses v0.1.13.  Thank you.

**Comment by duffdean** [comment]
Just wondering if there is either any update on when v0.1.14 will be released, or how we can install the plugin with the latest fix from @manuelsc ?
Still unable to use the spotify-oauth plugin due to the dependency on the legacy SDK.

**Comment by 21jordanmorris** [comment]
@duffdean did you ever resolve this issue?

**Comment by duffdean** [comment]
> @duffdean did you ever resolve this issue?

Unfortunately not no. I have tried removing the plugin and reinstalling as suggested by @manuelsc but it always points to the version with the dependency on the SDK. If you have any suggestions though that would be great, as I have had to deprecate the functionality that relies on this plugin.

**Comment by duffdean** [comment]
@21jordanmorris Was unable to resolve this, was also unable to install via npm, as I use Cordova plugin manger to install plugins. So whenever I try to install via `cordova plugins install cordova-spotify-oauth` it always downloads the version with the fault.
